name: CreditsSim
description: Credits viewer
version: 2.2.0
homepage: https://github.com/FarragoFiction/CreditsSim
author: jadedResearcher, paradoxLands

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  CreditsLib:
    git:  git://github.com/FarragoFiction/CharacterLib.git
  DollLibCorrect:
    git:
      url: git://github.com/FarragoFiction/DollLibCorrect.git
      ref: Dart-2.2.0
  CommonLib:
    git:
      url: git://github.com/FarragoFiction/CommonLib.git
      ref: Dart-2.2.0
  TextEngine:
    git:
      url: git://github.com/FarragoFiction/TextEngine.git
      ref: Dart-2.2.0
  RenderingLib:
    git:
      url: git://github.com/FarragoFiction/RenderingLib.git
      ref: Dart-2.2.0

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0