name: CreditsSim
description: Credits viewer
version: 2.2.0
homepage: https://github.com/FarragoFiction/CreditsSim
author: jadedResearcher, paradoxLands

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  CreditsLib:
    git:  git://github.com/FarragoFiction/CharacterLib.git
  RenderingLib:
    git: git://github.com/FarragoFiction/RenderingLib.git
  DollLibCorrect:
    git:  git://github.com/FarragoFiction/DollLibCorrect.git
  CommonLib:
    git: git://github.com/FarragoFiction/CommonLib.git
  TextEngine:
    git: git://github.com/FarragoFiction/TextEngine.git

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0